package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=BLOCK_JOB_PENDING, data={type=BlockJobType, id=str}}</pre>
 */
// QApiEventDescriptor{name=BLOCK_JOB_PENDING, data={type=BlockJobType, id=str}}
public class BlockJobPendingEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("type")
		@Nonnull
		public BlockJobType type;
		
		@JsonProperty("id")
		@Nonnull
		public java.lang.String id;
	}

	@JsonProperty("data")
	public Data data;
}
