package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-insert-medium, returns=null, data={id=str, node-name=str}}</pre>
 */
// QApiCommandDescriptor{name=blockdev-insert-medium, returns=null, data={id=str, node-name=str}}
public class BlockdevInsertMediumCommand extends QApiCommand<BlockdevInsertMediumCommand.Arguments, BlockdevInsertMediumCommand.Response> {
	/** Compound arguments to a BlockdevInsertMediumCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("id")
		@Nonnull
		public java.lang.String id;
		
		@JsonProperty("node-name")
		@Nonnull
		public java.lang.String nodeName;

		public Arguments() {
		}

		public Arguments(java.lang.String id, java.lang.String nodeName) {
			this.id = id;
			this.nodeName = nodeName;
		}
	}

	/** Response to a BlockdevInsertMediumCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevInsertMediumCommand. */
	public BlockdevInsertMediumCommand(@Nonnull BlockdevInsertMediumCommand.Arguments argument) {
		super("blockdev-insert-medium", Response.class, argument);
	}

	/** Constructs a new BlockdevInsertMediumCommand. */
	public BlockdevInsertMediumCommand(java.lang.String id, java.lang.String nodeName) {
		this(new Arguments(id, nodeName));
	}
}
