package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=input-send-event, returns=null, data={*device=str, *head=int, events=[InputEvent]}}</pre>
 */
// QApiCommandDescriptor{name=input-send-event, returns=null, data={*device=str, *head=int, events=[InputEvent]}}
public class InputSendEventCommand extends QApiCommand<InputSendEventCommand.Arguments, InputSendEventCommand.Response> {
	/** Compound arguments to a InputSendEventCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("device")
		@CheckForNull
		public java.lang.String device;
		
		@JsonProperty("head")
		@CheckForNull
		public java.lang.Long head;
		
		@JsonProperty("events")
		@Nonnull
		public java.util.List<InputEvent> events;

		public Arguments() {
		}

		public Arguments(java.lang.String device, java.lang.Long head, java.util.List<InputEvent> events) {
			this.device = device;
			this.head = head;
			this.events = events;
		}
	}

	/** Response to a InputSendEventCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new InputSendEventCommand. */
	public InputSendEventCommand(@Nonnull InputSendEventCommand.Arguments argument) {
		super("input-send-event", Response.class, argument);
	}

	/** Constructs a new InputSendEventCommand. */
	public InputSendEventCommand(java.lang.String device, java.lang.Long head, java.util.List<InputEvent> events) {
		this(new Arguments(device, head, events));
	}
}
