package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=trace-event-get-state, returns=[TraceEventInfo], data={name=str, *vcpu=int}}</pre>
 */
// QApiCommandDescriptor{name=trace-event-get-state, returns=[TraceEventInfo], data={name=str, *vcpu=int}}
public class TraceEventGetStateCommand extends QApiCommand<TraceEventGetStateCommand.Arguments, TraceEventGetStateCommand.Response> {
	/** Compound arguments to a TraceEventGetStateCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("name")
		@Nonnull
		public java.lang.String name;
		
		@JsonProperty("vcpu")
		@CheckForNull
		public java.lang.Long vcpu;

		public Arguments() {
		}

		public Arguments(java.lang.String name, java.lang.Long vcpu) {
			this.name = name;
			this.vcpu = vcpu;
		}
	}

	/** Response to a TraceEventGetStateCommand. */
	public static class Response extends QApiResponse<java.util.List<TraceEventInfo>> {
	}

	/** Constructs a new TraceEventGetStateCommand. */
	public TraceEventGetStateCommand(@Nonnull TraceEventGetStateCommand.Arguments argument) {
		super("trace-event-get-state", Response.class, argument);
	}

	/** Constructs a new TraceEventGetStateCommand. */
	public TraceEventGetStateCommand(java.lang.String name, java.lang.Long vcpu) {
		this(new Arguments(name, vcpu));
	}
}
