package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=WATCHDOG, data={action=WatchdogAction}}</pre>
 */
// QApiEventDescriptor{name=WATCHDOG, data={action=WatchdogAction}}
public class WatchdogEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("action")
		@Nonnull
		public WatchdogAction action;
	}

	@JsonProperty("data")
	public Data data;
}
