package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=MIGRATION_PASS, data={pass=int}}</pre>
 */
// QApiEventDescriptor{name=MIGRATION_PASS, data={pass=int}}
public class MigrationPassEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("pass")
		@Nonnull
		public long pass;
	}

	@JsonProperty("data")
	public Data data;
}
