package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-cpu-model-comparison, returns=CpuModelCompareInfo, data={modela=CpuModelInfo, modelb=CpuModelInfo}}</pre>
 */
// QApiCommandDescriptor{name=query-cpu-model-comparison, returns=CpuModelCompareInfo, data={modela=CpuModelInfo, modelb=CpuModelInfo}}
public class QueryCpuModelComparisonCommand extends QApiCommand<QueryCpuModelComparisonCommand.Arguments, QueryCpuModelComparisonCommand.Response> {
	/** Compound arguments to a QueryCpuModelComparisonCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("modela")
		@Nonnull
		public CpuModelInfo modela;
		
		@JsonProperty("modelb")
		@Nonnull
		public CpuModelInfo modelb;

		public Arguments() {
		}

		public Arguments(CpuModelInfo modela, CpuModelInfo modelb) {
			this.modela = modela;
			this.modelb = modelb;
		}
	}

	/** Response to a QueryCpuModelComparisonCommand. */
	public static class Response extends QApiResponse<CpuModelCompareInfo> {
	}

	/** Constructs a new QueryCpuModelComparisonCommand. */
	public QueryCpuModelComparisonCommand(@Nonnull QueryCpuModelComparisonCommand.Arguments argument) {
		super("query-cpu-model-comparison", Response.class, argument);
	}

	/** Constructs a new QueryCpuModelComparisonCommand. */
	public QueryCpuModelComparisonCommand(CpuModelInfo modela, CpuModelInfo modelb) {
		this(new Arguments(modela, modelb));
	}
}
