package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-cpu-model-baseline, returns=CpuModelBaselineInfo, data={modela=CpuModelInfo, modelb=CpuModelInfo}}</pre>
 */
// QApiCommandDescriptor{name=query-cpu-model-baseline, returns=CpuModelBaselineInfo, data={modela=CpuModelInfo, modelb=CpuModelInfo}}
public class QueryCpuModelBaselineCommand extends QApiCommand<QueryCpuModelBaselineCommand.Arguments, QueryCpuModelBaselineCommand.Response> {
	/** Compound arguments to a QueryCpuModelBaselineCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("modela")
		@Nonnull
		public CpuModelInfo modela;
		
		@JsonProperty("modelb")
		@Nonnull
		public CpuModelInfo modelb;

		public Arguments() {
		}

		public Arguments(CpuModelInfo modela, CpuModelInfo modelb) {
			this.modela = modela;
			this.modelb = modelb;
		}
	}

	/** Response to a QueryCpuModelBaselineCommand. */
	public static class Response extends QApiResponse<CpuModelBaselineInfo> {
	}

	/** Constructs a new QueryCpuModelBaselineCommand. */
	public QueryCpuModelBaselineCommand(@Nonnull QueryCpuModelBaselineCommand.Arguments argument) {
		super("query-cpu-model-baseline", Response.class, argument);
	}

	/** Constructs a new QueryCpuModelBaselineCommand. */
	public QueryCpuModelBaselineCommand(CpuModelInfo modela, CpuModelInfo modelb) {
		this(new Arguments(modela, modelb));
	}
}
