package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=xen-save-devices-state, returns=null, data={filename=str, *live=bool}}</pre>
 */
// QApiCommandDescriptor{name=xen-save-devices-state, returns=null, data={filename=str, *live=bool}}
public class XenSaveDevicesStateCommand extends QApiCommand<XenSaveDevicesStateCommand.Arguments, XenSaveDevicesStateCommand.Response> {
	/** Compound arguments to a XenSaveDevicesStateCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("filename")
		@Nonnull
		public java.lang.String filename;
		
		@JsonProperty("live")
		@CheckForNull
		public java.lang.Boolean live;

		public Arguments() {
		}

		public Arguments(java.lang.String filename, java.lang.Boolean live) {
			this.filename = filename;
			this.live = live;
		}
	}

	/** Response to a XenSaveDevicesStateCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new XenSaveDevicesStateCommand. */
	public XenSaveDevicesStateCommand(@Nonnull XenSaveDevicesStateCommand.Arguments argument) {
		super("xen-save-devices-state", Response.class, argument);
	}

	/** Constructs a new XenSaveDevicesStateCommand. */
	public XenSaveDevicesStateCommand(java.lang.String filename, java.lang.Boolean live) {
		this(new Arguments(filename, live));
	}
}
