package org.anarres.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;
import org.anarres.qemu.qapi.common.*;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=x-oob-test, returns=null, data={lock=bool}}</pre>
 */
// QApiCommandDescriptor{name=x-oob-test, returns=null, data={lock=bool}}
public class XOobTestCommand extends QApiCommand<XOobTestCommand.Arguments, XOobTestCommand.Response> {
	/** Compound arguments to a XOobTestCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("lock")
		@Nonnull
		public boolean lock;

		public Arguments() {
		}

		public Arguments(boolean lock) {
			this.lock = lock;
		}
	}

	/** Response to a XOobTestCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new XOobTestCommand. */
	public XOobTestCommand(@Nonnull XOobTestCommand.Arguments argument) {
		super("x-oob-test", Response.class, argument);
	}

	/** Constructs a new XOobTestCommand. */
	public XOobTestCommand(boolean lock) {
		this(new Arguments(lock));
	}
}
