package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=ACPI_DEVICE_OST, data={info=ACPIOSTInfo}}</pre>
 */
// QApiEventDescriptor{name=ACPI_DEVICE_OST, data={info=ACPIOSTInfo}}
public class AcpiDeviceOstEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("info")
		@Nonnull
		public ACPIOSTInfo info;
	}

	@JsonProperty("data")
	public Data data;
}
