package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=BALLOON_CHANGE, data={actual=int}}</pre>
 */
// QApiEventDescriptor{name=BALLOON_CHANGE, data={actual=int}}
public class BalloonChangeEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("actual")
		@Nonnull
		public long actual;
	}

	@JsonProperty("data")
	public Data data;
}
