package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-snapshot-sync, returns=null, data=BlockdevSnapshotSync}</pre>
 */
// QApiCommandDescriptor{name=blockdev-snapshot-sync, returns=null, data=BlockdevSnapshotSync}
public class BlockdevSnapshotSyncCommand extends QApiCommand<BlockdevSnapshotSync, BlockdevSnapshotSyncCommand.Response> {

	/** Response to a BlockdevSnapshotSyncCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevSnapshotSyncCommand. */
	public BlockdevSnapshotSyncCommand(@Nonnull BlockdevSnapshotSync argument) {
		super("blockdev-snapshot-sync", Response.class, argument);
	}

}
