package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-snapshot-internal-sync, returns=null, data=BlockdevSnapshotInternal}</pre>
 */
// QApiCommandDescriptor{name=blockdev-snapshot-internal-sync, returns=null, data=BlockdevSnapshotInternal}
public class BlockdevSnapshotInternalSyncCommand extends QApiCommand<BlockdevSnapshotInternal, BlockdevSnapshotInternalSyncCommand.Response> {

	/** Response to a BlockdevSnapshotInternalSyncCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevSnapshotInternalSyncCommand. */
	public BlockdevSnapshotInternalSyncCommand(@Nonnull BlockdevSnapshotInternal argument) {
		super("blockdev-snapshot-internal-sync", Response.class, argument);
	}

}
