package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=BlockdevCreateOptionsGluster, data={location=BlockdevOptionsGluster, size=size, *preallocation=PreallocMode}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=BlockdevCreateOptionsGluster, data={location=BlockdevOptionsGluster, size=size, *preallocation=PreallocMode}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockdevCreateOptionsGluster extends QApiType {

	
	@JsonProperty("location")
	@Nonnull
	public BlockdevOptionsGluster location;
	
	@JsonProperty("size")
	@Nonnull
	public long size;
	
	@JsonProperty("preallocation")
	@CheckForNull
	public PreallocMode preallocation;

	@Nonnull
	public BlockdevCreateOptionsGluster withLocation(BlockdevOptionsGluster value) {
		this.location = value;
		return this;
	}

	@Nonnull
	public BlockdevCreateOptionsGluster withSize(long value) {
		this.size = value;
		return this;
	}

	@Nonnull
	public BlockdevCreateOptionsGluster withPreallocation(PreallocMode value) {
		this.preallocation = value;
		return this;
	}

	public BlockdevCreateOptionsGluster() {
	}

	public BlockdevCreateOptionsGluster(BlockdevOptionsGluster location, long size, PreallocMode preallocation) {
		this.location = location;
		this.size = size;
		this.preallocation = preallocation;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("location");
		names.add("size");
		names.add("preallocation");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("location".equals(name))
			return location;
		if ("size".equals(name))
			return size;
		if ("preallocation".equals(name))
			return preallocation;
		return super.getFieldByName(name);
	}
}
