package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=BLOCK_IO_ERROR, data={device=str, *node-name=str, operation=IoOperationType, action=BlockErrorAction, *nospace=bool, reason=str}}</pre>
 */
// QApiEventDescriptor{name=BLOCK_IO_ERROR, data={device=str, *node-name=str, operation=IoOperationType, action=BlockErrorAction, *nospace=bool, reason=str}}
public class BlockIoErrorEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		
		@JsonProperty("node-name")
		@CheckForNull
		public java.lang.String nodeName;
		
		@JsonProperty("operation")
		@Nonnull
		public IoOperationType operation;
		
		@JsonProperty("action")
		@Nonnull
		public BlockErrorAction action;
		
		@JsonProperty("nospace")
		@CheckForNull
		public java.lang.Boolean nospace;
		
		@JsonProperty("reason")
		@Nonnull
		public java.lang.String reason;
	}

	@JsonProperty("data")
	public Data data;
}
