package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-open-tray, returns=null, data={*device=str, *id=str, *force=bool}}</pre>
 */
// QApiCommandDescriptor{name=blockdev-open-tray, returns=null, data={*device=str, *id=str, *force=bool}}
public class BlockdevOpenTrayCommand extends QApiCommand<BlockdevOpenTrayCommand.Arguments, BlockdevOpenTrayCommand.Response> {
	/** Compound arguments to a BlockdevOpenTrayCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("device")
		@CheckForNull
		public java.lang.String device;
		
		@JsonProperty("id")
		@CheckForNull
		public java.lang.String id;
		
		@JsonProperty("force")
		@CheckForNull
		public java.lang.Boolean force;

		public Arguments() {
		}

		public Arguments(java.lang.String device, java.lang.String id, java.lang.Boolean force) {
			this.device = device;
			this.id = id;
			this.force = force;
		}
	}

	/** Response to a BlockdevOpenTrayCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevOpenTrayCommand. */
	public BlockdevOpenTrayCommand(@Nonnull BlockdevOpenTrayCommand.Arguments argument) {
		super("blockdev-open-tray", Response.class, argument);
	}

	/** Constructs a new BlockdevOpenTrayCommand. */
	public BlockdevOpenTrayCommand(java.lang.String device, java.lang.String id, java.lang.Boolean force) {
		this(new Arguments(device, id, force));
	}
}
