package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-close-tray, returns=null, data={*device=str, *id=str}}</pre>
 */
// QApiCommandDescriptor{name=blockdev-close-tray, returns=null, data={*device=str, *id=str}}
public class BlockdevCloseTrayCommand extends QApiCommand<BlockdevCloseTrayCommand.Arguments, BlockdevCloseTrayCommand.Response> {
	/** Compound arguments to a BlockdevCloseTrayCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("device")
		@CheckForNull
		public java.lang.String device;
		
		@JsonProperty("id")
		@CheckForNull
		public java.lang.String id;

		public Arguments() {
		}

		public Arguments(java.lang.String device, java.lang.String id) {
			this.device = device;
			this.id = id;
		}
	}

	/** Response to a BlockdevCloseTrayCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevCloseTrayCommand. */
	public BlockdevCloseTrayCommand(@Nonnull BlockdevCloseTrayCommand.Arguments argument) {
		super("blockdev-close-tray", Response.class, argument);
	}

	/** Constructs a new BlockdevCloseTrayCommand. */
	public BlockdevCloseTrayCommand(java.lang.String device, java.lang.String id) {
		this(new Arguments(device, id));
	}
}
