package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=block-stream, returns=null, data={*job-id=str, device=str, *base=str, *base-node=str, *backing-file=str, *speed=int, *on-error=BlockdevOnError}}</pre>
 */
// QApiCommandDescriptor{name=block-stream, returns=null, data={*job-id=str, device=str, *base=str, *base-node=str, *backing-file=str, *speed=int, *on-error=BlockdevOnError}}
public class BlockStreamCommand extends QApiCommand<BlockStreamCommand.Arguments, BlockStreamCommand.Response> {
	/** Compound arguments to a BlockStreamCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("job-id")
		@CheckForNull
		public java.lang.String jobId;
		
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		
		@JsonProperty("base")
		@CheckForNull
		public java.lang.String base;
		
		@JsonProperty("base-node")
		@CheckForNull
		public java.lang.String baseNode;
		
		@JsonProperty("backing-file")
		@CheckForNull
		public java.lang.String backingFile;
		
		@JsonProperty("speed")
		@CheckForNull
		public java.lang.Long speed;
		
		@JsonProperty("on-error")
		@CheckForNull
		public BlockdevOnError onError;

		public Arguments() {
		}

		public Arguments(java.lang.String jobId, java.lang.String device, java.lang.String base, java.lang.String baseNode, java.lang.String backingFile, java.lang.Long speed, BlockdevOnError onError) {
			this.jobId = jobId;
			this.device = device;
			this.base = base;
			this.baseNode = baseNode;
			this.backingFile = backingFile;
			this.speed = speed;
			this.onError = onError;
		}
	}

	/** Response to a BlockStreamCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockStreamCommand. */
	public BlockStreamCommand(@Nonnull BlockStreamCommand.Arguments argument) {
		super("block-stream", Response.class, argument);
	}

	/** Constructs a new BlockStreamCommand. */
	public BlockStreamCommand(java.lang.String jobId, java.lang.String device, java.lang.String base, java.lang.String baseNode, java.lang.String backingFile, java.lang.Long speed, BlockdevOnError onError) {
		this(new Arguments(jobId, device, base, baseNode, backingFile, speed, onError));
	}
}
