package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-add, returns=null, data=BlockdevOptions}</pre>
 */
// QApiCommandDescriptor{name=blockdev-add, returns=null, data=BlockdevOptions}
public class BlockdevAddCommand extends QApiCommand<BlockdevOptions, BlockdevAddCommand.Response> {

	/** Response to a BlockdevAddCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevAddCommand. */
	public BlockdevAddCommand(@Nonnull BlockdevOptions argument) {
		super("blockdev-add", Response.class, argument);
	}

}
