package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=BlockJobInfo, data={type=str, device=str, len=int, offset=int, busy=bool, paused=bool, speed=int, io-status=BlockDeviceIoStatus, ready=bool, status=BlockJobStatus, auto-finalize=bool, auto-dismiss=bool}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=BlockJobInfo, data={type=str, device=str, len=int, offset=int, busy=bool, paused=bool, speed=int, io-status=BlockDeviceIoStatus, ready=bool, status=BlockJobStatus, auto-finalize=bool, auto-dismiss=bool}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class BlockJobInfo extends QApiType {

	
	@JsonProperty("type")
	@Nonnull
	public java.lang.String type;
	
	@JsonProperty("device")
	@Nonnull
	public java.lang.String device;
	
	@JsonProperty("len")
	@Nonnull
	public long len;
	
	@JsonProperty("offset")
	@Nonnull
	public long offset;
	
	@JsonProperty("busy")
	@Nonnull
	public boolean busy;
	
	@JsonProperty("paused")
	@Nonnull
	public boolean paused;
	
	@JsonProperty("speed")
	@Nonnull
	public long speed;
	
	@JsonProperty("io-status")
	@Nonnull
	public BlockDeviceIoStatus ioStatus;
	
	@JsonProperty("ready")
	@Nonnull
	public boolean ready;
	
	@JsonProperty("status")
	@Nonnull
	public BlockJobStatus status;
	
	@JsonProperty("auto-finalize")
	@Nonnull
	public boolean autoFinalize;
	
	@JsonProperty("auto-dismiss")
	@Nonnull
	public boolean autoDismiss;

	@Nonnull
	public BlockJobInfo withType(java.lang.String value) {
		this.type = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withDevice(java.lang.String value) {
		this.device = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withLen(long value) {
		this.len = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withOffset(long value) {
		this.offset = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withBusy(boolean value) {
		this.busy = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withPaused(boolean value) {
		this.paused = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withSpeed(long value) {
		this.speed = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withIoStatus(BlockDeviceIoStatus value) {
		this.ioStatus = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withReady(boolean value) {
		this.ready = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withStatus(BlockJobStatus value) {
		this.status = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withAutoFinalize(boolean value) {
		this.autoFinalize = value;
		return this;
	}

	@Nonnull
	public BlockJobInfo withAutoDismiss(boolean value) {
		this.autoDismiss = value;
		return this;
	}

	public BlockJobInfo() {
	}

	public BlockJobInfo(java.lang.String type, java.lang.String device, long len, long offset, boolean busy, boolean paused, long speed, BlockDeviceIoStatus ioStatus, boolean ready, BlockJobStatus status, boolean autoFinalize, boolean autoDismiss) {
		this.type = type;
		this.device = device;
		this.len = len;
		this.offset = offset;
		this.busy = busy;
		this.paused = paused;
		this.speed = speed;
		this.ioStatus = ioStatus;
		this.ready = ready;
		this.status = status;
		this.autoFinalize = autoFinalize;
		this.autoDismiss = autoDismiss;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("type");
		names.add("device");
		names.add("len");
		names.add("offset");
		names.add("busy");
		names.add("paused");
		names.add("speed");
		names.add("io-status");
		names.add("ready");
		names.add("status");
		names.add("auto-finalize");
		names.add("auto-dismiss");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("type".equals(name))
			return type;
		if ("device".equals(name))
			return device;
		if ("len".equals(name))
			return len;
		if ("offset".equals(name))
			return offset;
		if ("busy".equals(name))
			return busy;
		if ("paused".equals(name))
			return paused;
		if ("speed".equals(name))
			return speed;
		if ("io-status".equals(name))
			return ioStatus;
		if ("ready".equals(name))
			return ready;
		if ("status".equals(name))
			return status;
		if ("auto-finalize".equals(name))
			return autoFinalize;
		if ("auto-dismiss".equals(name))
			return autoDismiss;
		return super.getFieldByName(name);
	}
}
