package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=BLOCK_JOB_ERROR, data={device=str, operation=IoOperationType, action=BlockErrorAction}}</pre>
 */
// QApiEventDescriptor{name=BLOCK_JOB_ERROR, data={device=str, operation=IoOperationType, action=BlockErrorAction}}
public class BlockJobErrorEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		
		@JsonProperty("operation")
		@Nonnull
		public IoOperationType operation;
		
		@JsonProperty("action")
		@Nonnull
		public BlockErrorAction action;
	}

	@JsonProperty("data")
	public Data data;
}
