package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=BLOCK_JOB_READY, data={type=BlockJobType, device=str, len=int, offset=int, speed=int}}</pre>
 */
// QApiEventDescriptor{name=BLOCK_JOB_READY, data={type=BlockJobType, device=str, len=int, offset=int, speed=int}}
public class BlockJobReadyEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("type")
		@Nonnull
		public BlockJobType type;
		
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		
		@JsonProperty("len")
		@Nonnull
		public long len;
		
		@JsonProperty("offset")
		@Nonnull
		public long offset;
		
		@JsonProperty("speed")
		@Nonnull
		public long speed;
	}

	@JsonProperty("data")
	public Data data;
}
