package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=blockdev-snapshot, returns=null, data=BlockdevSnapshot}</pre>
 */
// QApiCommandDescriptor{name=blockdev-snapshot, returns=null, data=BlockdevSnapshot}
public class BlockdevSnapshotCommand extends QApiCommand<BlockdevSnapshot, BlockdevSnapshotCommand.Response> {

	/** Response to a BlockdevSnapshotCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new BlockdevSnapshotCommand. */
	public BlockdevSnapshotCommand(@Nonnull BlockdevSnapshot argument) {
		super("blockdev-snapshot", Response.class, argument);
	}

}
