package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=ChardevSpicePort, data={fqdn=str}, innerTypes=null, fields=null, base=ChardevCommon}</pre>
 */
// QApiStructDescriptor{name=ChardevSpicePort, data={fqdn=str}, innerTypes=null, fields=null, base=ChardevCommon}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class ChardevSpicePort extends ChardevCommon {

	
	@JsonProperty("fqdn")
	@Nonnull
	public java.lang.String fqdn;

	@Nonnull
	public ChardevSpicePort withFqdn(java.lang.String value) {
		this.fqdn = value;
		return this;
	}

	public ChardevSpicePort() {
	}

	public ChardevSpicePort(java.lang.String fqdn) {
		this.fqdn = fqdn;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("fqdn");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("fqdn".equals(name))
			return fqdn;
		return super.getFieldByName(name);
	}
}
