package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=chardev-remove, returns=null, data={id=str}}</pre>
 */
// QApiCommandDescriptor{name=chardev-remove, returns=null, data={id=str}}
public class ChardevRemoveCommand extends QApiCommand<ChardevRemoveCommand.Arguments, ChardevRemoveCommand.Response> {
	/** Compound arguments to a ChardevRemoveCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("id")
		@Nonnull
		public java.lang.String id;

		public Arguments() {
		}

		public Arguments(java.lang.String id) {
			this.id = id;
		}
	}

	/** Response to a ChardevRemoveCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new ChardevRemoveCommand. */
	public ChardevRemoveCommand(@Nonnull ChardevRemoveCommand.Arguments argument) {
		super("chardev-remove", Response.class, argument);
	}

	/** Constructs a new ChardevRemoveCommand. */
	public ChardevRemoveCommand(java.lang.String id) {
		this(new Arguments(id));
	}
}
