package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiTypeDescriptor{name=CpuInfoFastBase, data={cpu-index=int, qom-path=str, thread-id=int, *props=CpuInstanceProperties, arch=CpuInfoArch}, innerTypes=null}</pre>
 */
// QApiTypeDescriptor{name=CpuInfoFastBase, data={cpu-index=int, qom-path=str, thread-id=int, *props=CpuInstanceProperties, arch=CpuInfoArch}, innerTypes=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class CpuInfoFastBase extends QApiType {

	
	@JsonProperty("cpu-index")
	@Nonnull
	public long cpuIndex;
	
	@JsonProperty("qom-path")
	@Nonnull
	public java.lang.String qomPath;
	
	@JsonProperty("thread-id")
	@Nonnull
	public long threadId;
	
	@JsonProperty("props")
	@CheckForNull
	public CpuInstanceProperties props;
	
	@JsonProperty("arch")
	@Nonnull
	public CpuInfoArch arch;

	@Nonnull
	public CpuInfoFastBase withCpuIndex(long value) {
		this.cpuIndex = value;
		return this;
	}

	@Nonnull
	public CpuInfoFastBase withQomPath(java.lang.String value) {
		this.qomPath = value;
		return this;
	}

	@Nonnull
	public CpuInfoFastBase withThreadId(long value) {
		this.threadId = value;
		return this;
	}

	@Nonnull
	public CpuInfoFastBase withProps(CpuInstanceProperties value) {
		this.props = value;
		return this;
	}

	@Nonnull
	public CpuInfoFastBase withArch(CpuInfoArch value) {
		this.arch = value;
		return this;
	}

	public CpuInfoFastBase() {
	}

	public CpuInfoFastBase(long cpuIndex, java.lang.String qomPath, long threadId, CpuInstanceProperties props, CpuInfoArch arch) {
		this.cpuIndex = cpuIndex;
		this.qomPath = qomPath;
		this.threadId = threadId;
		this.props = props;
		this.arch = arch;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("cpu-index");
		names.add("qom-path");
		names.add("thread-id");
		names.add("props");
		names.add("arch");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("cpu-index".equals(name))
			return cpuIndex;
		if ("qom-path".equals(name))
			return qomPath;
		if ("thread-id".equals(name))
			return threadId;
		if ("props".equals(name))
			return props;
		if ("arch".equals(name))
			return arch;
		return super.getFieldByName(name);
	}
}
