package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=DEVICE_DELETED, data={*device=str, path=str}}</pre>
 */
// QApiEventDescriptor{name=DEVICE_DELETED, data={*device=str, path=str}}
public class DeviceDeletedEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("device")
		@CheckForNull
		public java.lang.String device;
		
		@JsonProperty("path")
		@Nonnull
		public java.lang.String path;
	}

	@JsonProperty("data")
	public Data data;
}
