package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=device_add, returns=null, data={driver=str, *bus=str, *id=str}}</pre>
 */
// QApiCommandDescriptor{name=device_add, returns=null, data={driver=str, *bus=str, *id=str}}
public class DeviceAddCommand extends QApiCommand<DeviceAddCommand.Arguments, DeviceAddCommand.Response> {
	/** Compound arguments to a DeviceAddCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("driver")
		@Nonnull
		public java.lang.String driver;
		
		@JsonProperty("bus")
		@CheckForNull
		public java.lang.String bus;
		
		@JsonProperty("id")
		@CheckForNull
		public java.lang.String id;

		public Arguments() {
		}

		public Arguments(java.lang.String driver, java.lang.String bus, java.lang.String id) {
			this.driver = driver;
			this.bus = bus;
			this.id = id;
		}
	}

	/** Response to a DeviceAddCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new DeviceAddCommand. */
	public DeviceAddCommand(@Nonnull DeviceAddCommand.Arguments argument) {
		super("device_add", Response.class, argument);
	}

	/** Constructs a new DeviceAddCommand. */
	public DeviceAddCommand(java.lang.String driver, java.lang.String bus, java.lang.String id) {
		this(new Arguments(driver, bus, id));
	}
}
