package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=DEVICE_TRAY_MOVED, data={device=str, id=str, tray-open=bool}}</pre>
 */
// QApiEventDescriptor{name=DEVICE_TRAY_MOVED, data={device=str, id=str, tray-open=bool}}
public class DeviceTrayMovedEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		
		@JsonProperty("id")
		@Nonnull
		public java.lang.String id;
		
		@JsonProperty("tray-open")
		@Nonnull
		public boolean trayOpen;
	}

	@JsonProperty("data")
	public Data data;
}
