package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=DUMP_COMPLETED, data={result=DumpQueryResult, *error=str}}</pre>
 */
// QApiEventDescriptor{name=DUMP_COMPLETED, data={result=DumpQueryResult, *error=str}}
public class DumpCompletedEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("result")
		@Nonnull
		public DumpQueryResult result;
		
		@JsonProperty("error")
		@CheckForNull
		public java.lang.String error;
	}

	@JsonProperty("data")
	public Data data;
}
