package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=MEM_UNPLUG_ERROR, data={device=str, msg=str}}</pre>
 */
// QApiEventDescriptor{name=MEM_UNPLUG_ERROR, data={device=str, msg=str}}
public class MemUnplugErrorEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("device")
		@Nonnull
		public java.lang.String device;
		
		@JsonProperty("msg")
		@Nonnull
		public java.lang.String msg;
	}

	@JsonProperty("data")
	public Data data;
}
