package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=migrate-start-postcopy, returns=null, data=null}</pre>
 */
// QApiCommandDescriptor{name=migrate-start-postcopy, returns=null, data=null}
public class MigrateStartPostcopyCommand extends QApiCommand<java.lang.Void, MigrateStartPostcopyCommand.Response> {

	/** Response to a MigrateStartPostcopyCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new MigrateStartPostcopyCommand. */
	public MigrateStartPostcopyCommand() {
		super("migrate-start-postcopy", Response.class, null);
	}

}
