package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEnumDescriptor{name=MirrorSyncMode, data=[top, full, none, incremental], fields=null}</pre>
 */
// QApiEnumDescriptor{name=MirrorSyncMode, data=[top, full, none, incremental], fields=null}
public enum MirrorSyncMode {
	top("top"),
	full("full"),
	none("none"),
	incremental("incremental"),
	__UNKNOWN("<unknown>");

	private final java.lang.String jsonValue;

	/* pp */ MirrorSyncMode(@Nonnull java.lang.String jsonValue) {
		this.jsonValue = jsonValue;
	}

	@JsonValue
	public java.lang.String getJsonValue() {
		return jsonValue;
	}
}
