package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=nbd-server-start, returns=null, data={addr=SocketAddressLegacy, *tls-creds=str}}</pre>
 */
// QApiCommandDescriptor{name=nbd-server-start, returns=null, data={addr=SocketAddressLegacy, *tls-creds=str}}
public class NbdServerStartCommand extends QApiCommand<NbdServerStartCommand.Arguments, NbdServerStartCommand.Response> {
	/** Compound arguments to a NbdServerStartCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("addr")
		@Nonnull
		public SocketAddressLegacy addr;
		
		@JsonProperty("tls-creds")
		@CheckForNull
		public java.lang.String tlsCreds;

		public Arguments() {
		}

		public Arguments(SocketAddressLegacy addr, java.lang.String tlsCreds) {
			this.addr = addr;
			this.tlsCreds = tlsCreds;
		}
	}

	/** Response to a NbdServerStartCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new NbdServerStartCommand. */
	public NbdServerStartCommand(@Nonnull NbdServerStartCommand.Arguments argument) {
		super("nbd-server-start", Response.class, argument);
	}

	/** Constructs a new NbdServerStartCommand. */
	public NbdServerStartCommand(SocketAddressLegacy addr, java.lang.String tlsCreds) {
		this(new Arguments(addr, tlsCreds));
	}
}
