package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=NIC_RX_FILTER_CHANGED, data={*name=str, path=str}}</pre>
 */
// QApiEventDescriptor{name=NIC_RX_FILTER_CHANGED, data={*name=str, path=str}}
public class NicRxFilterChangedEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("name")
		@CheckForNull
		public java.lang.String name;
		
		@JsonProperty("path")
		@Nonnull
		public java.lang.String path;
	}

	@JsonProperty("data")
	public Data data;
}
