package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-migrate-cache-size, returns=int, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-migrate-cache-size, returns=int, data=null}
public class QueryMigrateCacheSizeCommand extends QApiCommand<java.lang.Void, QueryMigrateCacheSizeCommand.Response> {

	/** Response to a QueryMigrateCacheSizeCommand. */
	public static class Response extends QApiResponse<java.lang.Long> {
	}

	/** Constructs a new QueryMigrateCacheSizeCommand. */
	public QueryMigrateCacheSizeCommand() {
		super("query-migrate-cache-size", Response.class, null);
	}

}
