package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-tpm-models, returns=[TpmModel], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-tpm-models, returns=[TpmModel], data=null}
public class QueryTpmModelsCommand extends QApiCommand<java.lang.Void, QueryTpmModelsCommand.Response> {

	/** Response to a QueryTpmModelsCommand. */
	public static class Response extends QApiResponse<java.util.List<TpmModel>> {
	}

	/** Constructs a new QueryTpmModelsCommand. */
	public QueryTpmModelsCommand() {
		super("query-tpm-models", Response.class, null);
	}

}
