package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-sev-capabilities, returns=SevCapability, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-sev-capabilities, returns=SevCapability, data=null}
public class QuerySevCapabilitiesCommand extends QApiCommand<java.lang.Void, QuerySevCapabilitiesCommand.Response> {

	/** Response to a QuerySevCapabilitiesCommand. */
	public static class Response extends QApiResponse<SevCapability> {
	}

	/** Constructs a new QuerySevCapabilitiesCommand. */
	public QuerySevCapabilitiesCommand() {
		super("query-sev-capabilities", Response.class, null);
	}

}
