package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-events, returns=[EventInfo], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-events, returns=[EventInfo], data=null}
public class QueryEventsCommand extends QApiCommand<java.lang.Void, QueryEventsCommand.Response> {

	/** Response to a QueryEventsCommand. */
	public static class Response extends QApiResponse<java.util.List<EventInfo>> {
	}

	/** Constructs a new QueryEventsCommand. */
	public QueryEventsCommand() {
		super("query-events", Response.class, null);
	}

}
