package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-tpm-types, returns=[TpmType], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-tpm-types, returns=[TpmType], data=null}
public class QueryTpmTypesCommand extends QApiCommand<java.lang.Void, QueryTpmTypesCommand.Response> {

	/** Response to a QueryTpmTypesCommand. */
	public static class Response extends QApiResponse<java.util.List<TpmType>> {
	}

	/** Constructs a new QueryTpmTypesCommand. */
	public QueryTpmTypesCommand() {
		super("query-tpm-types", Response.class, null);
	}

}
