package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-dump, returns=DumpQueryResult, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-dump, returns=DumpQueryResult, data=null}
public class QueryDumpCommand extends QApiCommand<java.lang.Void, QueryDumpCommand.Response> {

	/** Response to a QueryDumpCommand. */
	public static class Response extends QApiResponse<DumpQueryResult> {
	}

	/** Constructs a new QueryDumpCommand. */
	public QueryDumpCommand() {
		super("query-dump", Response.class, null);
	}

}
