package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-fdsets, returns=[FdsetInfo], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-fdsets, returns=[FdsetInfo], data=null}
public class QueryFdsetsCommand extends QApiCommand<java.lang.Void, QueryFdsetsCommand.Response> {

	/** Response to a QueryFdsetsCommand. */
	public static class Response extends QApiResponse<java.util.List<FdsetInfo>> {
	}

	/** Constructs a new QueryFdsetsCommand. */
	public QueryFdsetsCommand() {
		super("query-fdsets", Response.class, null);
	}

}
