package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-hotpluggable-cpus, returns=[HotpluggableCPU], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-hotpluggable-cpus, returns=[HotpluggableCPU], data=null}
public class QueryHotpluggableCpusCommand extends QApiCommand<java.lang.Void, QueryHotpluggableCpusCommand.Response> {

	/** Response to a QueryHotpluggableCpusCommand. */
	public static class Response extends QApiResponse<java.util.List<HotpluggableCPU>> {
	}

	/** Constructs a new QueryHotpluggableCpusCommand. */
	public QueryHotpluggableCpusCommand() {
		super("query-hotpluggable-cpus", Response.class, null);
	}

}
