package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-name, returns=NameInfo, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-name, returns=NameInfo, data=null}
public class QueryNameCommand extends QApiCommand<java.lang.Void, QueryNameCommand.Response> {

	/** Response to a QueryNameCommand. */
	public static class Response extends QApiResponse<NameInfo> {
	}

	/** Constructs a new QueryNameCommand. */
	public QueryNameCommand() {
		super("query-name", Response.class, null);
	}

}
