package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-block-jobs, returns=[BlockJobInfo], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-block-jobs, returns=[BlockJobInfo], data=null}
public class QueryBlockJobsCommand extends QApiCommand<java.lang.Void, QueryBlockJobsCommand.Response> {

	/** Response to a QueryBlockJobsCommand. */
	public static class Response extends QApiResponse<java.util.List<BlockJobInfo>> {
	}

	/** Constructs a new QueryBlockJobsCommand. */
	public QueryBlockJobsCommand() {
		super("query-block-jobs", Response.class, null);
	}

}
