package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-machines, returns=[MachineInfo], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-machines, returns=[MachineInfo], data=null}
public class QueryMachinesCommand extends QApiCommand<java.lang.Void, QueryMachinesCommand.Response> {

	/** Response to a QueryMachinesCommand. */
	public static class Response extends QApiResponse<java.util.List<MachineInfo>> {
	}

	/** Constructs a new QueryMachinesCommand. */
	public QueryMachinesCommand() {
		super("query-machines", Response.class, null);
	}

}
