package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-cpu-model-expansion, returns=CpuModelExpansionInfo, data={type=CpuModelExpansionType, model=CpuModelInfo}}</pre>
 */
// QApiCommandDescriptor{name=query-cpu-model-expansion, returns=CpuModelExpansionInfo, data={type=CpuModelExpansionType, model=CpuModelInfo}}
public class QueryCpuModelExpansionCommand extends QApiCommand<QueryCpuModelExpansionCommand.Arguments, QueryCpuModelExpansionCommand.Response> {
	/** Compound arguments to a QueryCpuModelExpansionCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("type")
		@Nonnull
		public CpuModelExpansionType type;
		
		@JsonProperty("model")
		@Nonnull
		public CpuModelInfo model;

		public Arguments() {
		}

		public Arguments(CpuModelExpansionType type, CpuModelInfo model) {
			this.type = type;
			this.model = model;
		}
	}

	/** Response to a QueryCpuModelExpansionCommand. */
	public static class Response extends QApiResponse<CpuModelExpansionInfo> {
	}

	/** Constructs a new QueryCpuModelExpansionCommand. */
	public QueryCpuModelExpansionCommand(@Nonnull QueryCpuModelExpansionCommand.Arguments argument) {
		super("query-cpu-model-expansion", Response.class, argument);
	}

	/** Constructs a new QueryCpuModelExpansionCommand. */
	public QueryCpuModelExpansionCommand(CpuModelExpansionType type, CpuModelInfo model) {
		this(new Arguments(type, model));
	}
}
