package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-target, returns=TargetInfo, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-target, returns=TargetInfo, data=null}
public class QueryTargetCommand extends QApiCommand<java.lang.Void, QueryTargetCommand.Response> {

	/** Response to a QueryTargetCommand. */
	public static class Response extends QApiResponse<TargetInfo> {
	}

	/** Constructs a new QueryTargetCommand. */
	public QueryTargetCommand() {
		super("query-target", Response.class, null);
	}

}
