package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-sev-launch-measure, returns=SevLaunchMeasureInfo, data=null}</pre>
 */
// QApiCommandDescriptor{name=query-sev-launch-measure, returns=SevLaunchMeasureInfo, data=null}
public class QuerySevLaunchMeasureCommand extends QApiCommand<java.lang.Void, QuerySevLaunchMeasureCommand.Response> {

	/** Response to a QuerySevLaunchMeasureCommand. */
	public static class Response extends QApiResponse<SevLaunchMeasureInfo> {
	}

	/** Constructs a new QuerySevLaunchMeasureCommand. */
	public QuerySevLaunchMeasureCommand() {
		super("query-sev-launch-measure", Response.class, null);
	}

}
