package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-block, returns=[BlockInfo], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-block, returns=[BlockInfo], data=null}
public class QueryBlockCommand extends QApiCommand<java.lang.Void, QueryBlockCommand.Response> {

	/** Response to a QueryBlockCommand. */
	public static class Response extends QApiResponse<java.util.List<BlockInfo>> {
	}

	/** Constructs a new QueryBlockCommand. */
	public QueryBlockCommand() {
		super("query-block", Response.class, null);
	}

}
