package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=query-gic-capabilities, returns=[GICCapability], data=null}</pre>
 */
// QApiCommandDescriptor{name=query-gic-capabilities, returns=[GICCapability], data=null}
public class QueryGicCapabilitiesCommand extends QApiCommand<java.lang.Void, QueryGicCapabilitiesCommand.Response> {

	/** Response to a QueryGicCapabilitiesCommand. */
	public static class Response extends QApiResponse<java.util.List<GICCapability>> {
	}

	/** Constructs a new QueryGicCapabilitiesCommand. */
	public QueryGicCapabilitiesCommand() {
		super("query-gic-capabilities", Response.class, null);
	}

}
