package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=quit, returns=null, data=null}</pre>
 */
// QApiCommandDescriptor{name=quit, returns=null, data=null}
public class QuitCommand extends QApiCommand<java.lang.Void, QuitCommand.Response> {

	/** Response to a QuitCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new QuitCommand. */
	public QuitCommand() {
		super("quit", Response.class, null);
	}

}
