package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=QUORUM_FAILURE, data={reference=str, sector-num=int, sectors-count=int}}</pre>
 */
// QApiEventDescriptor{name=QUORUM_FAILURE, data={reference=str, sector-num=int, sectors-count=int}}
public class QuorumFailureEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("reference")
		@Nonnull
		public java.lang.String reference;
		
		@JsonProperty("sector-num")
		@Nonnull
		public long sectorNum;
		
		@JsonProperty("sectors-count")
		@Nonnull
		public long sectorsCount;
	}

	@JsonProperty("data")
	public Data data;
}
