package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonUnwrapped;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiStructDescriptor{name=RockerOfDpaGroup, data={id=uint32, type=uint8, *vlan-id=uint16, *pport=uint32, *index=uint32, *out-pport=uint32, *group-id=uint32, *set-vlan-id=uint16, *pop-vlan=uint8, *group-ids=[uint32], *set-eth-src=str, *set-eth-dst=str, *ttl-check=uint8}, innerTypes=null, fields=null, base=null}</pre>
 */
// QApiStructDescriptor{name=RockerOfDpaGroup, data={id=uint32, type=uint8, *vlan-id=uint16, *pport=uint32, *index=uint32, *out-pport=uint32, *group-id=uint32, *set-vlan-id=uint16, *pop-vlan=uint8, *group-ids=[uint32], *set-eth-src=str, *set-eth-dst=str, *ttl-check=uint8}, innerTypes=null, fields=null, base=null}
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class RockerOfDpaGroup extends QApiType {

	
	@JsonProperty("id")
	@Nonnull
	public long id;
	
	@JsonProperty("type")
	@Nonnull
	public char type;
	
	@JsonProperty("vlan-id")
	@CheckForNull
	public java.lang.Integer vlanId;
	
	@JsonProperty("pport")
	@CheckForNull
	public java.lang.Long pport;
	
	@JsonProperty("index")
	@CheckForNull
	public java.lang.Long index;
	
	@JsonProperty("out-pport")
	@CheckForNull
	public java.lang.Long outPport;
	
	@JsonProperty("group-id")
	@CheckForNull
	public java.lang.Long groupId;
	
	@JsonProperty("set-vlan-id")
	@CheckForNull
	public java.lang.Integer setVlanId;
	
	@JsonProperty("pop-vlan")
	@CheckForNull
	public char popVlan;
	
	@JsonProperty("group-ids")
	@CheckForNull
	public java.util.List<java.lang.Long> groupIds;
	
	@JsonProperty("set-eth-src")
	@CheckForNull
	public java.lang.String setEthSrc;
	
	@JsonProperty("set-eth-dst")
	@CheckForNull
	public java.lang.String setEthDst;
	
	@JsonProperty("ttl-check")
	@CheckForNull
	public char ttlCheck;

	@Nonnull
	public RockerOfDpaGroup withId(long value) {
		this.id = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withType(char value) {
		this.type = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withVlanId(java.lang.Integer value) {
		this.vlanId = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withPport(java.lang.Long value) {
		this.pport = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withIndex(java.lang.Long value) {
		this.index = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withOutPport(java.lang.Long value) {
		this.outPport = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withGroupId(java.lang.Long value) {
		this.groupId = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withSetVlanId(java.lang.Integer value) {
		this.setVlanId = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withPopVlan(char value) {
		this.popVlan = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withGroupIds(java.util.List<java.lang.Long> value) {
		this.groupIds = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withSetEthSrc(java.lang.String value) {
		this.setEthSrc = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withSetEthDst(java.lang.String value) {
		this.setEthDst = value;
		return this;
	}

	@Nonnull
	public RockerOfDpaGroup withTtlCheck(char value) {
		this.ttlCheck = value;
		return this;
	}

	public RockerOfDpaGroup() {
	}

	public RockerOfDpaGroup(long id, char type, java.lang.Integer vlanId, java.lang.Long pport, java.lang.Long index, java.lang.Long outPport, java.lang.Long groupId, java.lang.Integer setVlanId, char popVlan, java.util.List<java.lang.Long> groupIds, java.lang.String setEthSrc, java.lang.String setEthDst, char ttlCheck) {
		this.id = id;
		this.type = type;
		this.vlanId = vlanId;
		this.pport = pport;
		this.index = index;
		this.outPport = outPport;
		this.groupId = groupId;
		this.setVlanId = setVlanId;
		this.popVlan = popVlan;
		this.groupIds = groupIds;
		this.setEthSrc = setEthSrc;
		this.setEthDst = setEthDst;
		this.ttlCheck = ttlCheck;
	}

	@JsonIgnore
	@Override
	public java.util.List<java.lang.String> getFieldNames() {
		java.util.List<java.lang.String> names = super.getFieldNames();
		names.add("id");
		names.add("type");
		names.add("vlan-id");
		names.add("pport");
		names.add("index");
		names.add("out-pport");
		names.add("group-id");
		names.add("set-vlan-id");
		names.add("pop-vlan");
		names.add("group-ids");
		names.add("set-eth-src");
		names.add("set-eth-dst");
		names.add("ttl-check");
		return names;
	}

	@Override
	public Object getFieldByName(@Nonnull java.lang.String name) throws NoSuchFieldException {
		if ("id".equals(name))
			return id;
		if ("type".equals(name))
			return type;
		if ("vlan-id".equals(name))
			return vlanId;
		if ("pport".equals(name))
			return pport;
		if ("index".equals(name))
			return index;
		if ("out-pport".equals(name))
			return outPport;
		if ("group-id".equals(name))
			return groupId;
		if ("set-vlan-id".equals(name))
			return setVlanId;
		if ("pop-vlan".equals(name))
			return popVlan;
		if ("group-ids".equals(name))
			return groupIds;
		if ("set-eth-src".equals(name))
			return setEthSrc;
		if ("set-eth-dst".equals(name))
			return setEthDst;
		if ("ttl-check".equals(name))
			return ttlCheck;
		return super.getFieldByName(name);
	}
}
