package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=RTC_CHANGE, data={offset=int}}</pre>
 */
// QApiEventDescriptor{name=RTC_CHANGE, data={offset=int}}
public class RtcChangeEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("offset")
		@Nonnull
		public long offset;
	}

	@JsonProperty("data")
	public Data data;
}
