package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=SPICE_DISCONNECTED, data={server=SpiceBasicInfo, client=SpiceBasicInfo}}</pre>
 */
// QApiEventDescriptor{name=SPICE_DISCONNECTED, data={server=SpiceBasicInfo, client=SpiceBasicInfo}}
public class SpiceDisconnectedEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("server")
		@Nonnull
		public SpiceBasicInfo server;
		
		@JsonProperty("client")
		@Nonnull
		public SpiceBasicInfo client;
	}

	@JsonProperty("data")
	public Data data;
}
