package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=SPICE_INITIALIZED, data={server=SpiceServerInfo, client=SpiceChannel}}</pre>
 */
// QApiEventDescriptor{name=SPICE_INITIALIZED, data={server=SpiceServerInfo, client=SpiceChannel}}
public class SpiceInitializedEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("server")
		@Nonnull
		public SpiceServerInfo server;
		
		@JsonProperty("client")
		@Nonnull
		public SpiceChannel client;
	}

	@JsonProperty("data")
	public Data data;
}
