package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=system_powerdown, returns=null, data=null}</pre>
 */
// QApiCommandDescriptor{name=system_powerdown, returns=null, data=null}
public class SystemPowerdownCommand extends QApiCommand<java.lang.Void, SystemPowerdownCommand.Response> {

	/** Response to a SystemPowerdownCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new SystemPowerdownCommand. */
	public SystemPowerdownCommand() {
		super("system_powerdown", Response.class, null);
	}

}
