package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=VSERPORT_CHANGE, data={id=str, open=bool}}</pre>
 */
// QApiEventDescriptor{name=VSERPORT_CHANGE, data={id=str, open=bool}}
public class VserportChangeEvent extends QApiEvent {

	public static class Data {
		
		@JsonProperty("id")
		@Nonnull
		public java.lang.String id;
		
		@JsonProperty("open")
		@Nonnull
		public boolean open;
	}

	@JsonProperty("data")
	public Data data;
}
