package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiEventDescriptor{name=WAKEUP, data=null}</pre>
 */
// QApiEventDescriptor{name=WAKEUP, data=null}
public class WakeupEvent extends QApiEvent {

}
