package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=xen-colo-do-checkpoint, returns=null, data=null}</pre>
 */
// QApiCommandDescriptor{name=xen-colo-do-checkpoint, returns=null, data=null}
public class XenColoDoCheckpointCommand extends QApiCommand<java.lang.Void, XenColoDoCheckpointCommand.Response> {

	/** Response to a XenColoDoCheckpointCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new XenColoDoCheckpointCommand. */
	public XenColoDoCheckpointCommand() {
		super("xen-colo-do-checkpoint", Response.class, null);
	}

}
