package com.lembed.lite.studio.qemu.qapi.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.lembed.lite.studio.qemu.qapi.common.*;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/**
 * Autogenerated class.
 *
 * <pre>QApiCommandDescriptor{name=xen-load-devices-state, returns=null, data={filename=str}}</pre>
 */
// QApiCommandDescriptor{name=xen-load-devices-state, returns=null, data={filename=str}}
public class XenLoadDevicesStateCommand extends QApiCommand<XenLoadDevicesStateCommand.Arguments, XenLoadDevicesStateCommand.Response> {
	/** Compound arguments to a XenLoadDevicesStateCommand. */
	@JsonInclude(JsonInclude.Include.NON_EMPTY)
	public static class Arguments {

		
		@JsonProperty("filename")
		@Nonnull
		public java.lang.String filename;

		public Arguments() {
		}

		public Arguments(java.lang.String filename) {
			this.filename = filename;
		}
	}

	/** Response to a XenLoadDevicesStateCommand. */
	public static class Response extends QApiResponse<java.lang.Void> {
	}

	/** Constructs a new XenLoadDevicesStateCommand. */
	public XenLoadDevicesStateCommand(@Nonnull XenLoadDevicesStateCommand.Arguments argument) {
		super("xen-load-devices-state", Response.class, argument);
	}

	/** Constructs a new XenLoadDevicesStateCommand. */
	public XenLoadDevicesStateCommand(java.lang.String filename) {
		this(new Arguments(filename));
	}
}
